export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const CHOOSE_CHARACTER = 'CHOOSE_CHARACTER';

export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const CHOOSE_PLANET = 'CHOOSE_PLANET'

export const FETCH_STARSHIPS_SUCCESS = 'FETCH_STARSHIPS_SUCCESS';
export const CHOOSE_STARSHIP= 'CHOOSE_STARSHIP'